"""initial persistent schema

Revision ID: 1253127b35e5
Revises:
Create Date: 2026-07-19 22:25:32.622877
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1253127b35e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_daily_quote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index_code', sa.String(length=16), nullable=False),
    sa.Column('index_name', sa.String(length=64), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('close_value', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('previous_close', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('change_percent', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_code', 'trade_date', 'source', name='uq_index_quote_code_date_source')
    )
    op.create_index(op.f('ix_index_daily_quote_index_code'), 'index_daily_quote', ['index_code'], unique=False)
    op.create_index(op.f('ix_index_daily_quote_trade_date'), 'index_daily_quote', ['trade_date'], unique=False)
    op.create_table('rule_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('exchange', sa.String(length=8), nullable=False),
    sa.Column('board', sa.String(length=16), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('event_count_threshold', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'effective_from', name='uq_rule_code_effective_from')
    )
    op.create_index(op.f('ix_rule_version_code'), 'rule_version', ['code'], unique=False)
    op.create_table('security_master',
    sa.Column('symbol', sa.String(length=6), nullable=False),
    sa.Column('exchange', sa.String(length=8), nullable=False),
    sa.Column('board', sa.String(length=16), nullable=False),
    sa.Column('board_label', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('list_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('benchmark_code', sa.String(length=16), nullable=False),
    sa.Column('benchmark_name', sa.String(length=64), nullable=False),
    sa.Column('price_limit_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_security_master_board'), 'security_master', ['board'], unique=False)
    op.create_index(op.f('ix_security_master_exchange'), 'security_master', ['exchange'], unique=False)
    op.create_table('alert_setting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_key', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=6), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['security_master.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_key', 'symbol', name='uq_alert_user_symbol')
    )
    op.create_index(op.f('ix_alert_setting_symbol'), 'alert_setting', ['symbol'], unique=False)
    op.create_index(op.f('ix_alert_setting_user_key'), 'alert_setting', ['user_key'], unique=False)
    op.create_table('anomaly_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=6), nullable=False),
    sa.Column('rule_version_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_label', sa.String(length=32), nullable=False),
    sa.Column('status_type', sa.String(length=16), nullable=False),
    sa.Column('rule_note', sa.String(length=256), nullable=False),
    sa.Column('quote_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_health', sa.String(length=16), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('day_change', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('display_change', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('stock_return', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('benchmark_return', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('deviation', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_version.id'], ),
    sa.ForeignKeyConstraint(['symbol'], ['security_master.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'mode', 'window_start', 'window_end', 'status', name='uq_anomaly_event_window')
    )
    op.create_index(op.f('ix_anomaly_event_mode'), 'anomaly_event', ['mode'], unique=False)
    op.create_index('ix_anomaly_event_mode_quote_time', 'anomaly_event', ['mode', 'quote_time'], unique=False)
    op.create_index(op.f('ix_anomaly_event_quote_time'), 'anomaly_event', ['quote_time'], unique=False)
    op.create_index(op.f('ix_anomaly_event_symbol'), 'anomaly_event', ['symbol'], unique=False)
    op.create_table('daily_quote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=6), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('previous_close', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('change_percent', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['security_master.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'trade_date', 'source', name='uq_daily_quote_symbol_date_source')
    )
    op.create_index(op.f('ix_daily_quote_symbol'), 'daily_quote', ['symbol'], unique=False)
    op.create_index(op.f('ix_daily_quote_trade_date'), 'daily_quote', ['trade_date'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_key', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['security_master.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_key', 'symbol', name='uq_watchlist_user_symbol')
    )
    op.create_index(op.f('ix_watchlist_symbol'), 'watchlist', ['symbol'], unique=False)
    op.create_index(op.f('ix_watchlist_user_key'), 'watchlist', ['user_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_user_key'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_symbol'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_daily_quote_trade_date'), table_name='daily_quote')
    op.drop_index(op.f('ix_daily_quote_symbol'), table_name='daily_quote')
    op.drop_table('daily_quote')
    op.drop_index(op.f('ix_anomaly_event_symbol'), table_name='anomaly_event')
    op.drop_index(op.f('ix_anomaly_event_quote_time'), table_name='anomaly_event')
    op.drop_index('ix_anomaly_event_mode_quote_time', table_name='anomaly_event')
    op.drop_index(op.f('ix_anomaly_event_mode'), table_name='anomaly_event')
    op.drop_table('anomaly_event')
    op.drop_index(op.f('ix_alert_setting_user_key'), table_name='alert_setting')
    op.drop_index(op.f('ix_alert_setting_symbol'), table_name='alert_setting')
    op.drop_table('alert_setting')
    op.drop_index(op.f('ix_security_master_exchange'), table_name='security_master')
    op.drop_index(op.f('ix_security_master_board'), table_name='security_master')
    op.drop_table('security_master')
    op.drop_index(op.f('ix_rule_version_code'), table_name='rule_version')
    op.drop_table('rule_version')
    op.drop_index(op.f('ix_index_daily_quote_trade_date'), table_name='index_daily_quote')
    op.drop_index(op.f('ix_index_daily_quote_index_code'), table_name='index_daily_quote')
    op.drop_table('index_daily_quote')
    # ### end Alembic commands ###
